package vista;

/**
 *
 * @author camil
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    String nombre;
    String rol;

    public FrmMenuPrincipal(String nombre, String rol) { // <--- Agregamos String nombre aquí
        initComponents();
        this.nombre = nombre;
        this.rol = rol;

        // Ahora 'nombre' ya funciona porque viene desde el paréntesis
        lblUsuarioLogueado.setText("Usuario conectado: " + nombre + " (" + rol + ")");
        setLocationRelativeTo(null);
        validarAdmin();

    }

    public void validarAdmin() {
        // SI EL USUARIO NO ES ADMIN
        if (!rol.equals("ADMIN")) {

            // Ocultar opciones solo para ADMIN
            itemInventario.setVisible(false);
            itemActualizarEstadoPaquete.setVisible(false);
            itemGestionReportes.setVisible(false);
            itemGestionSolicitudes.setVisible(false);
        } else {
            itemReportes.setVisible(false);
            itemSolicitarEnvio.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        desktopContenedor = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblUsuarioLogueado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemCerrarSesion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        itemSolicitudEnvio = new javax.swing.JMenu();
        itemInventario = new javax.swing.JMenuItem();
        itemRastreo = new javax.swing.JMenuItem();
        itemReportes = new javax.swing.JMenuItem();
        itemActualizarEstadoPaquete = new javax.swing.JMenuItem();
        itemGestionReportes = new javax.swing.JMenuItem();
        itemSolicitarEnvio = new javax.swing.JMenuItem();
        itemGestionSolicitudes = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("logo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuarioLogueado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioLogueado.setText("Usuario: [Nombre]");

        jLabel11.setText("© 2026 GoPack | Todos los derechos reservados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioLogueado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioLogueado)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo-MenuPrincipal.png"))); // NOI18N
        lblImagen.setText("jLabel1");

        desktopContenedor.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopContenedor.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopContenedorLayout = new javax.swing.GroupLayout(desktopContenedor);
        desktopContenedor.setLayout(desktopContenedorLayout);
        desktopContenedorLayout.setHorizontalGroup(
            desktopContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopContenedorLayout.setVerticalGroup(
            desktopContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopContenedorLayout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPrincipal.setText("Menú");
        menuPrincipal.add(jSeparator1);

        itemCerrarSesion.setText("Cerrar sesión");
        itemCerrarSesion.addActionListener(this::itemCerrarSesionActionPerformed);
        menuPrincipal.add(itemCerrarSesion);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        menuPrincipal.add(itemSalir);

        jMenuBar1.add(menuPrincipal);

        itemSolicitudEnvio.setText("Operaciones");

        itemInventario.setText("Ver Inventario ");
        itemInventario.addActionListener(this::itemInventarioActionPerformed);
        itemSolicitudEnvio.add(itemInventario);

        itemRastreo.setText("Rastrear Paquete");
        itemRastreo.addActionListener(this::itemRastreoActionPerformed);
        itemSolicitudEnvio.add(itemRastreo);

        itemReportes.setText("Reportes y Devoluciones");
        itemReportes.addActionListener(this::itemReportesActionPerformed);
        itemSolicitudEnvio.add(itemReportes);

        itemActualizarEstadoPaquete.setText("Actualizar Estado Paquete");
        itemActualizarEstadoPaquete.addActionListener(this::itemActualizarEstadoPaqueteActionPerformed);
        itemSolicitudEnvio.add(itemActualizarEstadoPaquete);

        itemGestionReportes.setText("Gestionar Reportes");
        itemGestionReportes.addActionListener(this::itemGestionReportesActionPerformed);
        itemSolicitudEnvio.add(itemGestionReportes);

        itemSolicitarEnvio.setText("Solicitar Envío");
        itemSolicitarEnvio.addActionListener(this::itemSolicitarEnvioActionPerformed);
        itemSolicitudEnvio.add(itemSolicitarEnvio);

        itemGestionSolicitudes.setText("Gestionar Solicitudes");
        itemGestionSolicitudes.addActionListener(this::itemGestionSolicitudesActionPerformed);
        itemSolicitudEnvio.add(itemGestionSolicitudes);

        jMenuBar1.add(itemSolicitudEnvio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas cerrar la sesión?",
                "Cerrar Sesión",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // 2. Crear una nueva instancia de tu ventana de Login
            // Asegúrate de que el nombre sea exactamente el de tu clase de Login
            FrmLogin login = new FrmLogin();

            // 3. Hacer visible el login
            login.setVisible(true);

            // 4. Cerrar (destruir) la ventana actual del Menú Principal
            this.dispose();
        }
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void itemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventarioActionPerformed
        // 1. Verificamos si ya está abierta
        for (javax.swing.JInternalFrame frame : desktopContenedor.getAllFrames()) {
            if (frame instanceof VtnInventario) {
                frame.toFront();
                return;
            }
        }

        VtnInventario vtn = new VtnInventario();
        desktopContenedor.add(vtn);

        vtn.setVisible(true);
    }//GEN-LAST:event_itemInventarioActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed

        // Preguntamos antes de cerrar para que no sea un accidente
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Desea cerrar la aplicación por completo?",
                "Confirmar salida",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); // Esto mata el proceso del programa
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemRastreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRastreoActionPerformed
        // 1. Verificamos si ya está abierta usando el ciclo que ya conoces
        for (javax.swing.JInternalFrame frame : desktopContenedor.getAllFrames()) {
            if (frame instanceof VtnRastreo) {
                frame.toFront(); // Si existe, la traemos al frente
                return; // Salimos del método para no crear una nueva
            }
        }

        // 2. Si no existe, la creamos
        VtnRastreo ventanaRastreo = new VtnRastreo();

        desktopContenedor.add(ventanaRastreo);

        ventanaRastreo.setVisible(true);
    }//GEN-LAST:event_itemRastreoActionPerformed

    private void itemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportesActionPerformed
        // TODO add your handling code here:
        // 1. Verificamos si ya está abierta usando el ciclo que ya conoces
        for (javax.swing.JInternalFrame frame : desktopContenedor.getAllFrames()) {
            if (frame instanceof VtnReportes) {
                frame.toFront(); // Si existe, la traemos al frente
                return; // Salimos del método para no crear una nueva
            }
        }

        // 2. Si no existe, la creamos
        VtnReportes ventanaReportes = new VtnReportes();

        desktopContenedor.add(ventanaReportes);

        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_itemReportesActionPerformed

    private void itemActualizarEstadoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarEstadoPaqueteActionPerformed
        // TODO add your handling code here:
        VtnActualizarEstado ventana
                = new VtnActualizarEstado();

        desktopContenedor.add(ventana);

        ventana.setVisible(true);
    }//GEN-LAST:event_itemActualizarEstadoPaqueteActionPerformed

    private void itemGestionReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionReportesActionPerformed
        // TODO add your handling code here:
        for (javax.swing.JInternalFrame frame
                : desktopContenedor.getAllFrames()) {

            if (frame instanceof VtnGestionReportes) {

                frame.toFront();

                return;
            }
        }

        VtnGestionReportes ventana
                = new VtnGestionReportes();

        desktopContenedor.add(ventana);

        ventana.setVisible(true);
    }//GEN-LAST:event_itemGestionReportesActionPerformed

    private void itemSolicitarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSolicitarEnvioActionPerformed
        // TODO add your handling code here:
        // Recorremos todas las ventanas abiertas
        for (javax.swing.JInternalFrame frame
                : desktopContenedor.getAllFrames()) {

            // Si la ventana ya está abierta
            if (frame instanceof VtnSolicitudEnvio) {

                // La traemos al frente
                frame.toFront();

                return;
            }
        }

        // Si NO existe, la creamos
        VtnSolicitudEnvio ventana
                = new VtnSolicitudEnvio(this.nombre);

        // La agregamos al contenedor principal
        desktopContenedor.add(ventana);

        // La hacemos visible
        ventana.setVisible(true);
    }//GEN-LAST:event_itemSolicitarEnvioActionPerformed

    private void itemGestionSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionSolicitudesActionPerformed
        // TODO add your handling code here:
        // Recorremos las ventanas abiertas
        for (javax.swing.JInternalFrame frame
                : desktopContenedor.getAllFrames()) {

            // Si la ventana ya existe
            if (frame instanceof VtnGestionSolicitudes) {

                // La traemos al frente
                frame.toFront();

                return;
            }
        }

        // Si no existe, la creamos
        VtnGestionSolicitudes ventana
                = new VtnGestionSolicitudes();

        // La agregamos al contenedor
        desktopContenedor.add(ventana);

        // La mostramos
        ventana.setVisible(true);
    }//GEN-LAST:event_itemGestionSolicitudesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopContenedor;
    private javax.swing.JMenuItem itemActualizarEstadoPaquete;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemGestionReportes;
    private javax.swing.JMenuItem itemGestionSolicitudes;
    private javax.swing.JMenuItem itemInventario;
    private javax.swing.JMenuItem itemRastreo;
    private javax.swing.JMenuItem itemReportes;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSolicitarEnvio;
    private javax.swing.JMenu itemSolicitudEnvio;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUsuarioLogueado;
    private javax.swing.JMenu menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
