/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.PaqueteController;
import javax.swing.JOptionPane;

/**
 *
 * @author camil
 */
public class VtnActualizarEstado extends javax.swing.JInternalFrame {

    PaqueteController paqueteControl
            = new PaqueteController();

    /**
     * Creates new form VtnActualizarEstado
     */
    public VtnActualizarEstado() {
        initComponents();
    cbNuevaCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{ "Digite una guía primero..." }));
    cbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{ "Seleccionar...", "En Bodega", "En Despacho", "En Ruta", "Entregado" }));
    limpiarCampos();
    }

    private void limpiarCampos() {
    txtGuia.setText("");
    cbNuevoEstado.setSelectedIndex(0);
    cbNuevaCiudad.removeAllItems();
    cbNuevaCiudad.addItem("Digite una guía primero...");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGuia = new javax.swing.JTextField();
        cbNuevoEstado = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbNuevaCiudad = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualización de Estado de Paquetes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Actualización de Estado");

        txtGuia.setText("jTextField1");
        txtGuia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGuiaKeyReleased(evt);
            }
        });

        cbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Guia de paquete:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nuevo estado:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        jLabel12.setText("© 2026 GoPack | Todos los derechos reservados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ubicaion Actual");

        cbNuevaCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(336, 336, 336))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(104, 104, 104))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel3)
                                .addGap(217, 217, 217)
                                .addComponent(jLabel4)
                                .addGap(237, 237, 237)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(147, 147, 147)
                                .addComponent(cbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(cbNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        // Obtener datos
      String guia = txtGuia.getText().trim();
    String nuevoEstado = cbNuevoEstado.getSelectedItem().toString();
    String nuevaCiudad = cbNuevaCiudad.getSelectedItem().toString();

    if (guia.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese una guía.");
        return;
    }

    if (nuevoEstado.equals("Seleccionar...")) {
        JOptionPane.showMessageDialog(this, "Seleccione un estado.");
        return;
    }

if (nuevaCiudad.equals("Seleccionar...") || nuevaCiudad.equals("Digite una guía primero...") || nuevaCiudad.equals("Guía no encontrada")) {
    JOptionPane.showMessageDialog(this, "Seleccione una ubicación válida cargada desde la guía.");
    return;
}

    boolean actualizado = paqueteControl.actualizarEstadoPaquete(guia, nuevoEstado, nuevaCiudad);

    if (actualizado) {
        JOptionPane.showMessageDialog(this, "Estado y ubicación actualizados correctamente.");
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró paquete con esta guía.");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtGuiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGuiaKeyReleased
       String guia = txtGuia.getText().trim();

    if (guia.isEmpty()) {
        cbNuevaCiudad.removeAllItems();
        cbNuevaCiudad.addItem("Digite una guía primero...");
    } else {
        cbNuevaCiudad.removeAllItems();
        cbNuevaCiudad.addItem("Seleccionar...");
        
        if (guia.length() >= 4) { 
            modelo.Paquete p = paqueteControl.buscarPaquetePorGuia(guia);
            
            if (p != null) {
                cbNuevaCiudad.addItem(p.getCiudadOrigen());
                if (!p.getCiudadOrigen().equalsIgnoreCase(p.getCiudadDestino())) {
                    cbNuevaCiudad.addItem(p.getCiudadDestino());
                }
            } else {
                cbNuevaCiudad.removeAllItems();
                cbNuevaCiudad.addItem("Guía no encontrada");
            }
        }
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtGuiaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbNuevaCiudad;
    private javax.swing.JComboBox<String> cbNuevoEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtGuia;
    // End of variables declaration//GEN-END:variables
}
