/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import dao.SolicitudEnvioDAO;
import controlador.PaqueteController;
import java.util.ArrayList;
import render.RenderEstadoSolicitudes;

/**
 *
 * @author camil
 */
public class VtnGestionSolicitudes extends javax.swing.JInternalFrame {

    private ArrayList<Integer> listaIdsOcultos = new ArrayList<>();

    /**
     * Creates new form GestionSolicitudes
     */
    public VtnGestionSolicitudes() {
        initComponents();
        cargarSolicitudes();
    }

    public void cargarSolicitudes() {

        try {
            listaIdsOcultos.clear();   // limpiamos la lista cada vez que se recargan los datos

            dao.SolicitudEnvioDAO dao = new dao.SolicitudEnvioDAO();  // crear DAO

            java.sql.ResultSet rs = dao.listarSolicitudes();  // obtenemos resultados de mysql

            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel() {  // modelo de la tabla

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            modelo.addColumn("Guía");
            modelo.addColumn("Remitente");
            modelo.addColumn("Destinatario");
            modelo.addColumn("Origen");
            modelo.addColumn("Destino");
            modelo.addColumn("Dirección");
            modelo.addColumn("Peso(Kg)");
            modelo.addColumn("Costo Envío");
            modelo.addColumn("Tipo");
            modelo.addColumn("Estado");
            modelo.addColumn("Fecha");


            while (rs.next()) {
                // guardamos el ID en nuestra lista oculta (mismo orden que las filas)
                listaIdsOcultos.add(rs.getInt("id_solicitud"));

                // añadimos a la tabla solo lo que queremos que el usuario vea
                modelo.addRow(new Object[]{
                    rs.getString("guia"),
                    rs.getString("remitente"),
                    rs.getString("destinatario"),
                    rs.getString("ciudad_origen"),
                    rs.getString("ciudad_destino"),
                    rs.getString("direccion_entrega"),
                    rs.getDouble("peso"),
                    "$ " + rs.getDouble("costo_envio"),
                    rs.getString("tipo_envio"),
                    rs.getString("estado"),
                    rs.getTimestamp("fecha_registro")
                });
            }


            tablaSolicitudes.setModel(modelo);  // poner datos de la tabla

            tablaSolicitudes
                    .getColumnModel()
                    .getColumn(9)
                    .setCellRenderer(new RenderEstadoSolicitudes());

        } catch (Exception e) {
            System.out.println("Error cargar solicitudes: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de Solicitudes");

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Remitente", "Destinatario", "Ciudad origen", "Ciudad destino", "Dirección", "Peso(Kg)", "Tipo envío", "Estado", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tablaSolicitudes);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Gestión de Solicitudes");

        jLabel11.setText("© 2026 GoPack | Todos los derechos reservados");

        btnAceptar.setBackground(new java.awt.Color(0, 153, 0));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar solicitud");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnRechazar.setBackground(new java.awt.Color(153, 0, 0));
        btnRechazar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRechazar.setForeground(new java.awt.Color(255, 255, 255));
        btnRechazar.setText("Rechazar solicitud");
        btnRechazar.addActionListener(this::btnRechazarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)
                        .addContainerGap(356, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(29, 29, 29)
                .addComponent(btnRechazar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnRechazar))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int fila = tablaSolicitudes.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una solicitud");
            return;
        }


        String estado = tablaSolicitudes.getValueAt(fila, 9).toString();

        if (estado.equals("ACEPTADA")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta solicitud ya fue aceptada");
            return;
        }

        if (estado.equals("RECHAZADA")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No puedes aceptar una solicitud rechazada");
            return;
        }

        int idSolicitud = listaIdsOcultos.get(fila);

        SolicitudEnvioDAO dao = new SolicitudEnvioDAO();
        String guia = dao.generarGuia();

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Aceptar esta solicitud?",
                "Confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        boolean resultado = dao.aceptarSolicitud(idSolicitud, guia);

        if (resultado) {
            // extraemos los datos de la fila usando los indices correctos
            String remitente = tablaSolicitudes.getValueAt(fila, 1).toString();
            String destinatario = tablaSolicitudes.getValueAt(fila, 2).toString();
            String ciudadOrigen = tablaSolicitudes.getValueAt(fila, 3).toString();
            String ciudadDestino = tablaSolicitudes.getValueAt(fila, 4).toString();
            String direccion = tablaSolicitudes.getValueAt(fila, 5).toString();
            String peso = tablaSolicitudes.getValueAt(fila, 6).toString();
            String costoEnvio = tablaSolicitudes.getValueAt(fila, 7).toString();
            String tipo = tablaSolicitudes.getValueAt(fila, 8).toString();

            controlador.PaqueteController paqueteController = new controlador.PaqueteController(); // instanciamos el controlador

            paqueteController.guardarPaquete(
                    guia,
                    remitente,
                    destinatario,
                    direccion,
                    peso,
                    costoEnvio, 
                    tipo,
                    ciudadOrigen,
                    ciudadDestino
            );

            javax.swing.JOptionPane.showMessageDialog(this, "Solicitud aceptada\nGuía: " + guia);
            cargarSolicitudes();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        // TODO add your handling code here:

        int fila = tablaSolicitudes.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una solicitud");
            return;
        }

        // el estado esta en el indice 8
        String estado = tablaSolicitudes.getValueAt(fila, 9).toString();

        if (estado.equals("RECHAZADA")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta solicitud ya fue rechazada");
            return;
        }

        if (estado.equals("ACEPTADA")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No puedes rechazar una solicitud aceptada");
            return;
        }

        
        int idSolicitud = listaIdsOcultos.get(fila);

        SolicitudEnvioDAO dao = new SolicitudEnvioDAO();

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Rechazar esta solicitud?",
                "Confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        boolean resultado = dao.rechazarSolicitud(idSolicitud);

        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Solicitud rechazada");
            cargarSolicitudes();
        }
    }//GEN-LAST:event_btnRechazarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
