/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.GestionReporteController;
import javax.swing.JOptionPane;

/**
 *
 * @author camil
 */
public class VtnGestionReportes extends javax.swing.JInternalFrame {

    GestionReporteController control
            = new GestionReporteController();

    /**
     * Creates new form VtnGestionReportes
     */
    public VtnGestionReportes() {
        initComponents();
        configurarSeleccionTabla();
        cargarTabla();

        cbEstadoReporte.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[]{
                            "Seleccionar...",
                            "Pendiente",
                            "En Revisión",
                            "Resuelto"
                        }
                )
        );
    }
    private void configurarSeleccionTabla() {
    tblGestionReportes.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int fila = tblGestionReportes.getSelectedRow();
            if (fila != -1) {
                // obtenemos el estado de la columna 6 (donde está el texto)
                String estado = tblGestionReportes.getValueAt(fila, 6).toString();
                
                // aqui controlamos el combobox de la vista directamente:
                if ("Resuelto".equalsIgnoreCase(estado)) {
                    cbEstadoReporte.setEnabled(false);
                } else {
                    cbEstadoReporte.setEnabled(true);
                }
            }
        }
    });
}

    private void cargarTabla() {

        tblGestionReportes.setModel(
                control.mostrarReportes()
        );

        // aqui aplicamos el render (los colores de las tablas)
        tblGestionReportes.getColumnModel()
                .getColumn(6)
                .setCellRenderer(
                        new render.RenderEstadoReportes()
                );

        tblGestionReportes.clearSelection();

        cbEstadoReporte.setSelectedIndex(0);
        ocultarColumnaId();
    }
    private void ocultarColumnaId() {
    // verificamos que la tabla tenga al menos una columna para evitar errores
    if (tblGestionReportes.getColumnCount() > 0) {
        // la columna 0 es el ID. Modificamos su ancho visual a 0.
        tblGestionReportes.getColumnModel().getColumn(0).setMinWidth(0);
        tblGestionReportes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblGestionReportes.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionReportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbEstadoReporte = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnActualizarEstadoReporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión Reportes y Devoluciones");

        tblGestionReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Guía", "Motivo", "Descripción", "Evidencia", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGestionReportes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Reportes y Devoluciones");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        jLabel12.setText("© 2026 GoPack | Todos los derechos reservados");

        cbEstadoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Pendiente", "En Revisión", "Resuelto" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Estado de reporte:");

        btnActualizarEstadoReporte.setBackground(new java.awt.Color(0, 153, 0));
        btnActualizarEstadoReporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarEstadoReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarEstadoReporte.setText("Actualizar");
        btnActualizarEstadoReporte.addActionListener(this::btnActualizarEstadoReporteActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione un reporte de la tabla para actualizar su estado");

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver evidencia");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(325, 325, 325))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbEstadoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnActualizarEstadoReporte)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1)))
                        .addGap(0, 584, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstadoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarEstadoReporte)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarEstadoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEstadoReporteActionPerformed
        // TODO add your handling code here:
        int fila
                = tblGestionReportes.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un reporte."
            );

            return;
        }

        int idReporte
                = Integer.parseInt(
                        tblGestionReportes.getValueAt(
                                fila,
                                0
                        ).toString()
                );

        String nuevoEstado
                = cbEstadoReporte
                        .getSelectedItem()
                        .toString();

        boolean actualizado
                = control.actualizarEstadoGestionReporte(
                        idReporte,
                        nuevoEstado
                );

        if (actualizado) {

            JOptionPane.showMessageDialog(
                    this,
                    "Estado actualizado."
                    
            );
            

            cargarTabla();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al actualizar."
            );
        }
    
    }//GEN-LAST:event_btnActualizarEstadoReporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int filaSeleccionada = tblGestionReportes.getSelectedRow();
    
    // si no ha seleccionado ninguna fila, le avisamos
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un reporte de la tabla primero.");
        return;
    }
    
    // obtenemos el valor de la columna "guia". 
    // OJO: cambia el número 1 por la posición exacta de la columna Guía en tu tabla (empezando desde 0).

    String guia = tblGestionReportes.getValueAt(filaSeleccionada, 1).toString();
    
    // abrimos la ventana interna mandándole la guía que capturamos
    javax.swing.JDesktopPane desktopPane = this.getDesktopPane();
    if (desktopPane != null) {
        // pasamos la variable 'guia' dentro del parentesis
        VtnVerEvidencia vtn = new VtnVerEvidencia(guia);
        
        desktopPane.add(vtn);
        vtn.setVisible(true);
        try {
            vtn.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            System.out.println("Error al enfocar: " + e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEstadoReporte;
    private javax.swing.JComboBox<String> cbEstadoReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGestionReportes;
    // End of variables declaration//GEN-END:variables
}
