/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

// Importaciones necesarias
import conexion.ConexionInfo;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import controlador.GestionReporteController;
import controlador.PaqueteController;

/**
 *
 * @author camil
 */
public class VtnReportes extends javax.swing.JInternalFrame {

    File archivoSeleccionado;
    ConexionInfo info;

    GestionReporteController control = new GestionReporteController();
    PaqueteController paqueteControl = new PaqueteController();

    /**
     * Creates new form VtnReportes
     */
    public VtnReportes() {
        initComponents();
        info = new ConexionInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbMotivoReporte = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEnviarReporte = new javax.swing.JButton();
        txtGuia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        btnAdjuntar = new javax.swing.JButton();
        lblPrevisualizacion = new javax.swing.JLabel();
        lblRutaArchivo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reportes y Devoluciones");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Reportes y Devoluciones");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        jLabel12.setText("© 2026 GoPack | Todos los derechos reservados");

        cbMotivoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "El artículo tienes fallas o no funciona", "Descripción inexacta del sitio web", "Mejor precio disponible", "El pedido llegó tarde", "Piezas faltantes o rotas", "Recibí un articulo incorrecto" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Selecciona un motivo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Describe detalladamente el problema:");

        jLabel4.setText("Para mejorar nuestra capacidad de ayudarte y trabajar para encontrar");

        jLabel5.setText("una solución, podemos compartir la información que nos proporciones con");

        jLabel6.setText("el socio comercial. Tu privacidad y seguridad son nuerstra prioridad.");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("NOTA:");

        btnEnviarReporte.setBackground(new java.awt.Color(0, 153, 0));
        btnEnviarReporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnviarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarReporte.setText("Enviar");
        btnEnviarReporte.addActionListener(this::btnEnviarReporteActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ingrese la guía del paquete:");

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcion);

        btnAdjuntar.setBackground(new java.awt.Color(0, 102, 255));
        btnAdjuntar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdjuntar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdjuntar.setText("Adjuntar imagen");
        btnAdjuntar.addActionListener(this::btnAdjuntarActionPerformed);

        lblPrevisualizacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRutaArchivo.setText("No hay archivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))
                                .addGap(102, 102, 102))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(btnAdjuntar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addComponent(lblRutaArchivo)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(175, 175, 175))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGuia)
                                        .addGap(104, 104, 104)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPrevisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbMotivoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(84, 84, 84)
                                        .addComponent(btnEnviarReporte)))))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMotivoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviarReporte))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRutaArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrevisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdjuntar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarActionPerformed
        // TODO add your handling code here:
        // 1. Crear el selector de archivos
        JFileChooser selector = new JFileChooser();
        // 2. Crear un filtro para que solo muestre imágenes
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("Imágenes (JPG, PNG)", "jpg", "png", "jpeg");
        selector.setFileFilter(filtroImagen);

        // 3. Abrir la ventana y capturar la respuesta del usuario
        int respuesta = selector.showOpenDialog(this);

        // 4. Si el usuario hizo clic en "Abrir/Aceptar"
        if (respuesta == JFileChooser.APPROVE_OPTION) {

            // Obtener el archivo real que seleccionó
            archivoSeleccionado = selector.getSelectedFile();

            lblRutaArchivo.setText("Archivo adjunto");
            // ---- CÓDIGO PARA MOSTRAR LA PREVISUALIZACIÓN ----
            // Crear un ImageIcon con la ruta
            ImageIcon iconOriginal = new ImageIcon(archivoSeleccionado.getAbsolutePath());

            // Redimensionar la imagen para que quepa en el JLabel de previsualización (ej: 100x100)
            Image imagenRedimensionada = iconOriginal.getImage().getScaledInstance(
                    lblPrevisualizacion.getWidth(),
                    lblPrevisualizacion.getHeight(),
                    Image.SCALE_SMOOTH);

            // Poner la imagen redimensionada en el JLabel
            lblPrevisualizacion.setIcon(new ImageIcon(imagenRedimensionada));
        }
    }//GEN-LAST:event_btnAdjuntarActionPerformed

    private void limpiarFormulario() {
        txtGuia.setText("");
        cbMotivoReporte.setSelectedIndex(0);
        txtaDescripcion.setText("");
        lblRutaArchivo.setText("No hay archivo");
        lblPrevisualizacion.setIcon(null);
        lblPrevisualizacion.setText("");
    }

private void guardarReportes() {
    String nombreFinalImagen = null;

    if (archivoSeleccionado != null) {
        try {
            // 1. Validar o crear la carpeta física dentro de tu proyecto
            File carpetaEvidencias = new File("src/recursos/evidencias");
            if (!carpetaEvidencias.exists()) {
                carpetaEvidencias.mkdirs();
            }

            // 2. Generar un nombre único con el Timestamp actual para evitar duplicados
            long timestamp = System.currentTimeMillis();
            String nombreOriginal = archivoSeleccionado.getName();
            String extension = nombreOriginal.substring(nombreOriginal.lastIndexOf("."));
            
            // Ejemplo de resultado: "evidencia_1777278822543.jpg"
            nombreFinalImagen = "evidencia_" + timestamp + extension;

            // 3. Copiar físicamente el archivo del usuario a la carpeta del proyecto
            File archivoDestino = new File(carpetaEvidencias, nombreFinalImagen);
            java.nio.file.Files.copy(
                archivoSeleccionado.toPath(), 
                archivoDestino.toPath(), 
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar y guardar la imagen física: " + e.getMessage());
            return; 
        }
    }

    // 4. Guardar en la Base de Datos llamando a tu procedimiento almacenado
    try (Connection con = conexion.ConexionBD.conectar()) {
        String sql = "CALL insertar_reporte(?, ?, ?, ?)";
        try (PreparedStatement prm = con.prepareStatement(sql)) {
            prm.setString(1, txtGuia.getText().trim());
            prm.setString(2, cbMotivoReporte.getSelectedItem().toString());
            prm.setString(3, txtaDescripcion.getText().trim());
            prm.setString(4, nombreFinalImagen); // Se guarda el nombre corto limpio
            
            prm.execute();
        }

        JOptionPane.showMessageDialog(this, "Reporte enviado correctamente.");
        limpiarFormulario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error en Base de Datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    private void btnEnviarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarReporteActionPerformed

        // TODO add your handling code here:
        // Obtener guía
        String guia = txtGuia.getText().trim();

        // 2. Obtener la ruta de la imagen que guardamos en lblRutaArchivo
        String rutaOrigen = lblRutaArchivo.getText();

        if (!txtGuia.getText().equals("")
                && !txtaDescripcion.getText().equals("")
                && cbMotivoReporte.getSelectedIndex() != 0
                && archivoSeleccionado != null) {

            // VALIDAR SI LA GUÍA EXISTE
            if (!paqueteControl.existeGuia(guia)) {

                JOptionPane.showMessageDialog(
                        this,
                        "La guía ingresada no existe."
                );

                return;
            }

            // VALIDAR SI YA EXISTE UN REPORTE ACTIVO
            if (control.existeReporteActivo(guia)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Esta guía ya tiene un reporte activo."
                );

                return;
            }

            // GUARDAR REPORTE
            guardarReportes();

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte enviado"
            );

            limpiarFormulario();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Complete todos los campos"
            );
        }


    }//GEN-LAST:event_btnEnviarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntar;
    private javax.swing.JButton btnEnviarReporte;
    private javax.swing.JComboBox<String> cbMotivoReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrevisualizacion;
    private javax.swing.JLabel lblRutaArchivo;
    private javax.swing.JTextField txtGuia;
    private javax.swing.JTextArea txtaDescripcion;
    // End of variables declaration//GEN-END:variables
}
