/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.SolicitudEnvioController;
import javax.swing.JOptionPane;

/**
 *
 * @author camil
 */
public class VtnSolicitudEnvio extends javax.swing.JInternalFrame {

    SolicitudEnvioController control
            = new SolicitudEnvioController();

    private void limpiarCampos() {

        // LIMPIAR CAJAS DE TEXTO
        txtDestinatario.setText("");

        txtDireccion.setText("");

        txtPeso.setText("");

        // REINICIAR COMBOBOX
        cbCiudadOrigen.setSelectedIndex(0);

        cbCiudadDestino.setSelectedIndex(0);

        cbTipoEnvio.setSelectedIndex(0);
    }

    private void calcularCostoEnvio() {

        try {

            // =====================================================
            // OBTENER DATOS
            // =====================================================
            String origen = cbCiudadOrigen
                    .getSelectedItem()
                    .toString();

            String destino = cbCiudadDestino
                    .getSelectedItem()
                    .toString();

            String pesoTexto = txtPeso
                    .getText()
                    .trim();

            // =====================================================
            // VALIDAR DATOS
            // =====================================================
            if (origen.equals("Seleccionar...")
                    || destino.equals("Seleccionar...")
                    || pesoTexto.isEmpty()) {

                lblCostoEnvio.setText("$ 0");
                return;
            }

            // =====================================================
            // CONVERTIR PESO
            // =====================================================
            double peso = Double.parseDouble(
                    pesoTexto.replace(",", ".")
            );

            // =====================================================
            // COSTO BASE
            // =====================================================
            double costo = 5000;

            // =====================================================
            // SI LAS CIUDADES SON DIFERENTES
            // =====================================================
            if (!origen.equals(destino)) {

                costo += 10000;
            }

            // =====================================================
            // COSTO SEGÚN PESO
            // =====================================================
            costo += peso * 2000;

            // =====================================================
            // MOSTRAR COSTO
            // =====================================================
            lblCostoEnvio.setText(
                    "$ " + String.format("%.0f", costo)
            );

        } catch (Exception e) {

            lblCostoEnvio.setText("$ 0");
        }
    }

    /**
     * Creates new form VtnSolicitudEnvio
     */
    public VtnSolicitudEnvio(String nombreUsuario) {
        initComponents();
        limpiarCampos();
        txtRemitente.setText(nombreUsuario);
        txtRemitente.setEditable(false);
        cbCiudadOrigen.addActionListener(e -> {
            calcularCostoEnvio();
        });

        cbCiudadDestino.addActionListener(e -> {
            calcularCostoEnvio();
        });

        txtPeso.addKeyListener(
                new java.awt.event.KeyAdapter() {

            @Override
            public void keyReleased(
                    java.awt.event.KeyEvent evt
            ) {

                calcularCostoEnvio();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRemitente = new javax.swing.JTextField();
        cbCiudadOrigen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbCiudadDestino = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbTipoEnvio = new javax.swing.JComboBox<>();
        txtDestinatario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSolicitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblCostoTitulo = new javax.swing.JLabel();
        lblCostoEnvio = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Solicitud de Envío");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Remitente:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel13.setText("jLabel5");

        txtRemitente.setText("jTextField2");

        cbCiudadOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Armenia", "Barranquilla", "Bogotá", "Bucaramanga", "Cali", "Cartagena", "Cúcuta", "Ibagué", "Manizales", "Medellín", "Montería", "Neiva", "Pasto", "Pereira", "Popayán", "Santa Marta", "Sincelejo", "Tunja", "Valledupar", "Villavicencio" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Destinatario:");

        cbCiudadDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Armenia", "Barranquilla", "Bogotá", "Bucaramanga", "Cali", "Cartagena", "Cúcuta", "Ibagué", "Manizales", "Medellín", "Montería", "Neiva", "Pasto", "Pereira", "Popayán", "Santa Marta", "Sincelejo", "Tunja", "Valledupar", "Villavicencio" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Peso (kg):");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Ciudad de destino:");

        txtPeso.setText("jTextField1");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de envío:");

        cbTipoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Frágil", "Pesado", "Documentos" }));

        txtDestinatario.setText("jTextField3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Dirección de Entrega:");

        btnSolicitar.setBackground(new java.awt.Color(0, 153, 0));
        btnSolicitar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitar.setText("Solicitar envío");
        btnSolicitar.addActionListener(this::btnSolicitarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Solicitud de Envío");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ciudad de origen:");

        txtDireccion.setText("jTextField3");

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel11.setText("© 2026 GoPack | Todos los derechos reservados");

        lblCostoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCostoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblCostoTitulo.setText("Costo estimado:");

        lblCostoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCostoEnvio.setForeground(new java.awt.Color(0, 102, 0));
        lblCostoEnvio.setText("$ 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(cbCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(cbCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnSolicitar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDestinatario))
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCostoTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCostoEnvio))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCostoTitulo)
                                .addComponent(lblCostoEnvio)))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        // TODO add your handling code here:
        // =====================================================
        // ENVIAR LOS DATOS AL CONTROLLER
        // =====================================================
        boolean resultado = control.registrarSolicitud(
                txtRemitente.getText(),
                txtDestinatario.getText(),
                cbCiudadOrigen.getSelectedItem().toString(),
                cbCiudadDestino.getSelectedItem().toString(),
                txtDireccion.getText(),
                txtPeso.getText(),
                cbTipoEnvio.getSelectedItem().toString()
        );

        // =====================================================
        // SI TODO SALE BIEN
        // =====================================================
        if (resultado) {

            JOptionPane.showMessageDialog(
                    this,
                    "Solicitud enviada correctamente"
            );

            // =====================================================
            // LIMPIAR FORMULARIO
            // =====================================================
            limpiarCampos();
        }
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<String> cbCiudadDestino;
    private javax.swing.JComboBox<String> cbCiudadOrigen;
    private javax.swing.JComboBox<String> cbTipoEnvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCostoEnvio;
    private javax.swing.JLabel lblCostoTitulo;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtRemitente;
    // End of variables declaration//GEN-END:variables
}
