/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.io.File;

/**
 *
 * @author ASUS
 */
public class VtnVerEvidencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form VtnVerEvidencia
     */
    public VtnVerEvidencia(String guiaRecibida) {
        initComponents();
 
        this.setClosable(true);      // Permite que se pueda cerrar con la X
        this.setIconifiable(true);  // Permite minimizarla
        this.setMaximizable(false); // Evitamos que la maximicen para que no se deforme el diseño
        this.setResizable(false);
        
        txtGuia.setText(guiaRecibida);
        txtGuia.setEditable(false);  // No se puede modificar el texto
        txtGuia.setEnabled(false);
        if (guiaRecibida != null && !guiaRecibida.trim().isEmpty()) {
            cargarFotoDesdeTabla(guiaRecibida);
        }
    }
private void cargarFotoDesdeTabla(String guia) {
        controlador.GestionReporteController controlReportes = new controlador.GestionReporteController();
        
        // Preguntar al controlador el nombre del archivo asignado a la guía
        String nombreArchivo = controlReportes.obtenerNombreEvidencia(guia);
        
        if (nombreArchivo == null || nombreArchivo.trim().isEmpty()) {
            lblFotoEvidencia.setIcon(null);
            lblFotoEvidencia.setText("No hay evidencia registrada para la guía: " + guia);
            return;
        }

        // Armar la ruta apuntando a la carpeta de tu proyecto
        String rutaImagen = "src/recursos/evidencias/" + nombreArchivo; 
        
        try {
            File archivo = new File(rutaImagen);
            if (!archivo.exists()) {
                lblFotoEvidencia.setIcon(null);
                lblFotoEvidencia.setText("El archivo físico no existe en el servidor.");
                return;
            }

            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(rutaImagen);
            
            // --- TRUCO VISUAL: Dimensiones fijas perfectas para que la foto no se corte ---
            int anchoLabel = 380;
            int altoLabel = 260;

            // Escalar la imagen usando un suavizado de alta calidad (SCALE_SMOOTH)
            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                anchoLabel, 
                altoLabel, 
                java.awt.Image.SCALE_SMOOTH
            );
            
            lblFotoEvidencia.setText(""); 
            lblFotoEvidencia.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            
            // Forzar a la ventana a redibujar los componentes de inmediato
            this.repaint();
            
        } catch (Exception e) {
            lblFotoEvidencia.setIcon(null);
            lblFotoEvidencia.setText("Error al renderizar la imagen.");
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGuia = new javax.swing.JTextField();
        lblFotoEvidencia = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Guia");

        lblFotoEvidencia.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFotoEvidencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 195, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblFotoEvidencia)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFotoEvidencia;
    private javax.swing.JTextField txtGuia;
    // End of variables declaration//GEN-END:variables
}
